[project]
name = "cli-samples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "agno>=1.3.3",
    "dotenv>=0.9.9",
    "duckduckgo-search>=8.0.1",
    "groq>=0.22.0",
    "yfinance>=0.2.55",
]
